/*
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Answer:  4613732
 * Completed on Thu, 18 Nov 2021, 15:09
 */


#include <iostream>

int sol(int n) {
	int x = 1;	// First term
	int y = 2;	// Second term
	int z = 0;	// Nth term

	int sum = y;
	
	while(z < n) {
		if(z % 2 == 0) {
			sum += z;
		}
		
		z = x + y;
		
		x = y;
		y = z;
	}
	return sum;
}

int main() {
	int n = 4000000;

	std::cout << sol(n) << '\n';

	return 0;
}
